"use client";

import { useState } from "react";
import { BankConfig } from "@/lib/banks/types";
import { validateBankForm, isValid, FormValues } from "@/lib/validation";
import { supabase } from "@/lib/supabase";
import { FormField } from "./FormField";
import { SubmitConfirmation } from "./SubmitConfirmation";

interface BankFormProps {
  bank: BankConfig;
}

export function BankForm({ bank }: BankFormProps) {
  const [values, setValues] = useState<FormValues>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [result, setResult] = useState<{ serialNo: number | null } | null>(
    null
  );

  const visibleFields = bank.fields.filter((f) => !f.autoGenerated);
  const hasAutoSerial = bank.fields.some(
    (f) => f.autoGenerated && f.key === "sr_no"
  );

  function handleChange(key: string, value: string) {
    setValues((prev) => ({ ...prev, [key]: value }));
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setSubmitError(null);

    const validationErrors = validateBankForm(bank, values);
    setErrors(validationErrors);
    if (!isValid(validationErrors)) return;

    setSubmitting(true);
    try {
      let serialNo: number | null = null;

      if (hasAutoSerial) {
        const { data, error } = await supabase.rpc("next_serial", {
          bank_name: bank.slug,
        });
        if (error) throw error;
        serialNo = data as number;
      }

      // Build the jsonb payload from only the fields the worker actually
      // entered (visible fields), keyed by FieldConfig.key.
      const payload: Record<string, string> = {};
      for (const field of visibleFields) {
        payload[field.key] = (values[field.key] ?? "").trim();
      }

      const { error: insertError } = await supabase.from("submissions").insert({
        bank: bank.slug,
        serial_no: serialNo,
        data: payload,
      });

      if (insertError) throw insertError;

      setResult({ serialNo });
    } catch (err) {
      setSubmitError(
        err instanceof Error
          ? `Could not submit: ${err.message}`
          : "Could not submit. Please try again."
      );
    } finally {
      setSubmitting(false);
    }
  }

  if (result) {
    return (
      <SubmitConfirmation
        bankDisplayName={bank.displayName}
        serialNo={result.serialNo}
      />
    );
  }

  return (
    <form onSubmit={handleSubmit} className="mx-auto max-w-md p-6">
      <h1 className="mb-6 text-center text-2xl font-semibold text-slate-900">
        {bank.displayName}
      </h1>

      {visibleFields.map((field) => (
        <FormField
          key={field.key}
          field={field}
          value={values[field.key] ?? ""}
          error={errors[field.key]}
          onChange={handleChange}
        />
      ))}

      {submitError && (
        <p className="mb-4 text-base text-red-600">{submitError}</p>
      )}

      <button
        type="submit"
        disabled={submitting}
        className="w-full rounded-2xl bg-blue-600 py-5 text-xl font-semibold text-white shadow-sm active:bg-blue-700 disabled:opacity-60"
      >
        {submitting ? "Submitting..." : "SUBMIT"}
      </button>
    </form>
  );
}
