import { BankConfig, FieldConfig } from "./banks/types";

export type FormValues = Record<string, string>;
export type ValidationErrors = Record<string, string>;

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/; // matches <input type="date"> value format
const TIME_RE = /^\d{2}:\d{2}(:\d{2})?$/; // matches <input type="time"> value format

function validateField(field: FieldConfig, rawValue: string | undefined): string | null {
  const value = (rawValue ?? "").trim();

  if (field.required && value === "") {
    return `${field.label} is required.`;
  }

  // Empty + not required → no further checks needed.
  if (value === "") return null;

  switch (field.type) {
    case "date":
      if (!DATE_RE.test(value)) return `${field.label} must be a valid date.`;
      break;
    case "time":
      if (!TIME_RE.test(value)) return `${field.label} must be a valid time.`;
      break;
    case "number":
      if (Number.isNaN(Number(value))) return `${field.label} must be a number.`;
      break;
    case "text":
    default:
      break;
  }

  return null;
}

/**
 * Validates form values against a bank's field configuration.
 * Auto-generated fields (e.g. Sr. No.) are skipped — they are never
 * collected from the worker and are populated server-side.
 */
export function validateBankForm(
  bank: BankConfig,
  values: FormValues
): ValidationErrors {
  const errors: ValidationErrors = {};

  for (const field of bank.fields) {
    if (field.autoGenerated) continue;
    const error = validateField(field, values[field.key]);
    if (error) errors[field.key] = error;
  }

  return errors;
}

export function isValid(errors: ValidationErrors): boolean {
  return Object.keys(errors).length === 0;
}
