import { BankConfig } from "./types";

export const hdfc: BankConfig = {
  slug: "hdfc",
  displayName: "HDFC Bank",
  fields: [
    { key: "sr_no", label: "Sr. No.", type: "number", required: true, autoGenerated: true },
    { key: "date", label: "Date", type: "date", required: true },
    { key: "branch", label: "Branch", type: "text", required: true },
    { key: "customer_name", label: "Customer Name", type: "text", required: true },
    { key: "in_time", label: "In Time", type: "time", required: true },
    { key: "out_time", label: "Out Time", type: "time", required: true },
    { key: "loan_no", label: "Loan No.", type: "text", required: true },
    { key: "amount", label: "Amount", type: "number", required: true },
    { key: "valuer_name", label: "Valuer Name", type: "text", required: true },
  ],
};
