export type FieldType = "text" | "date" | "time" | "number";

export interface FieldConfig {
  /** Stable key used in the submissions.data JSONB payload and Excel column maps. */
  key: string;
  /** Exact label as supplied by the client. Do not rename. */
  label: string;
  type: FieldType;
  required: boolean;
  /**
   * True only for fields the system generates itself (HDFC/Jana "Sr. No.").
   * Auto-generated fields are never rendered in the worker form and are
   * never included in client-side validation.
   */
  autoGenerated?: boolean;
}

export interface BankConfig {
  /** Slug used in routes and the submissions.bank column, e.g. "hdfc". */
  slug: "hdfc" | "jana" | "hdb" | "kotak";
  /** Display name shown on the bank selection screen. */
  displayName: string;
  fields: FieldConfig[];
}

export type BankSlug = BankConfig["slug"];
