export type FieldType = "text" | "date" | "time" | "number";

export interface FieldConfig {
  /** Stable key used in the submissions.data JSONB payload and Excel column maps. */
  key: string;
  /** Exact label as supplied by the client. */
  label: string;
  type: FieldType;
  required: boolean;
  /** True only for fields generated by the system. */
  autoGenerated?: boolean;
}

export interface BankConfig {
  /** Slug used in routes and the submissions.bank column. */
  slug: "hdfc" | "jana" | "hdb" | "kotak" | "hdfc_fix" | "jana_fix";
  displayName: string;
  fields: FieldConfig[];
}

export type BankSlug = BankConfig["slug"];
